type Palette {
    paletteName: String!
    id: ID!
    emoji: String!
    colors: [Color!] @relation
    
}

type Color {
    name: ID!
    color: String!
    palette: Palette!
}

type Query {
    allPalettes: [Palette!]!
    allColors: [Color!]!
}